### ISSUE TITLE
Agree on Parity configuration options

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/blockchain#546]
Due to #493 the different locations where we defined configuration options for _Parit_ have been merged into a single file. This includes the options of the former `validator-config.toml` file. These were not used before, since the _Docker_ image only extended the `user-config.toml` with own snippets and additional parameter. The "new" options of the validator configuration must be decided on, if we actually want them and if they should be applied for validators only (comment them out per default).
The diff of new options which weren't used before is the following (this ignores the `author` option, which is part of #533):

```toml
[parity]
# Save pending local transactions to disk to be restored whenever the node restarts.
no_persistent_txqueue = false

[network]
# Parity will maintain at most 100 peers.
max_peers = 100

[mining]
# New transactions will not cause a new pending block to be created.
reseal_on_txs = "none"
# Minimum amount of Wei per GAS to be paid for a transaction to be accepted for mining. Overrides --usd-per-tx.
min_gas_price = 1
# Maximum number of transactions per sender in the queue. By default it's 1% of the entire queue, but not less than 16.
tx_queue_per_sender = 100
```
